package de.paul2708.worm.columns.properties;

import de.paul2708.worm.columns.generator.ValueGenerator;

import java.lang.reflect.InvocationTargetException;

public class AutoGeneratedProperty implements ColumnProperty {

    private final Class<? extends ValueGenerator<?>> generatorClazz;

    public AutoGeneratedProperty(Class<? extends ValueGenerator<?>> generatorClazz) {
        this.generatorClazz = generatorClazz;
    }

    public ValueGenerator<?> createGenerator() {
        try {
            return generatorClazz.getConstructor().newInstance();
        } catch (InstantiationException | InvocationTargetException | NoSuchMethodException |
                 IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}