package de.paul2708.worm;

import de.paul2708.worm.columns.*;
import de.paul2708.worm.columns.generator.UUIDGenerator;

import java.util.UUID;

@Table("fleets")
public class Fleet {

    @Identifier
    @AutoGenerated(UUIDGenerator.class)
    @Column("id")
    private UUID id;

    @Column("name")
    private String name;

    @ForeignKey
    @Column("owner_id")
    private Person person;

    public Fleet() {

    }

    public Fleet(String name, Person person) {
        this.name = name;
        this.person = person;
    }

    public UUID getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Person getPerson() {
        return person;
    }
}
