package de.paul2708.worm;

import de.paul2708.worm.columns.*;
import de.paul2708.worm.columns.generator.IntegerGenerator;

import java.time.LocalDateTime;

@Entity("rounds")
public class Round {

    @Identifier
    @AutoGenerated(IntegerGenerator.class)
    @Column("id")
    private int id;

    @TimeZone("Europe/Berlin")
    @Column("start_time")
    private LocalDateTime startTime;

    @TimeZone("Europe/Berlin")
    @Column("end_time")
    private LocalDateTime endTime;

    @CreatedAt
    @TimeZone("Europe/Berlin")
    @Column("created_at")
    private LocalDateTime createdAt;

    @UpdatedAt
    @TimeZone("Europe/Berlin")
    @Column("updated_at")
    private LocalDateTime updatedAt;

    public Round() {

    }

    public Round(LocalDateTime startTime, LocalDateTime endTime) {
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    public int getId() {
        return id;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public LocalDateTime getEndTime() {
        return endTime;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
}
