package de.paul2708.worm.example;

import de.paul2708.worm.columns.*;

import java.util.UUID;

@Table("persons")
public class Person {

    @Column("id")
    @PrimaryKey
    @AutoGenerated
    private int id;

	@Column("uuid")
	private UUID uuid;

    @Column("name")
    @MaxLength(255)
    private String name;

    @Column("age")
    private int age;

    public Person() {

    }

    public Person(UUID uuid, String name, int age) {
		this.uuid = uuid;
        this.name = name;
        this.age = age;
    }

    public int getId() {
        return id;
    }

	public UUID getUuid() {
		return uuid;
	}

	public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}
