package de.paul2708.worm.example;

import de.paul2708.worm.columns.*;

@Table("persons")
public class Person {

    @PrimaryKey("person_id")
    @AutoGenerated
    private int id;

    @Column("name")
    @MaxLength(255)
    private String name;

    @Column("age")
    private int age;

    public Person() {

    }

    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}
