package de.paul2708.worm.example;

import de.paul2708.worm.columns.AutoGenerated;
import de.paul2708.worm.columns.Column;
import de.paul2708.worm.columns.PrimaryKey;
import de.paul2708.worm.columns.Table;

@Table("persons")
public class Person {

    @PrimaryKey("id")
    @AutoGenerated
    private int id;

    @Column("name")
    private final String name;

    @Column("age")
    private final int age;

    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}
