package de.paul2708.worm.columns;

import java.util.Objects;

public final class PrimaryKeyAttribute extends ColumnAttribute {

    private final String fieldName;
    private final boolean autoGenerated;

    public PrimaryKeyAttribute(String fieldName, String columnName, Class<?> fieldType, boolean autoGenerated) {
        super(columnName, fieldType);

        this.fieldName = fieldName;
        this.autoGenerated = autoGenerated;
    }

    public String fieldName() {
        return fieldName;
    }

    public boolean autoGenerated() {
        return autoGenerated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        PrimaryKeyAttribute that = (PrimaryKeyAttribute) o;
        return autoGenerated == that.autoGenerated && Objects.equals(fieldName, that.fieldName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), fieldName, autoGenerated);
    }

    @Override
    public String toString() {
        return "PrimaryKeyAttribute{" +
                "fieldName='" + fieldName + '\'' +
                ", autoGenerated=" + autoGenerated +
                '}';
    }
}