package de.paul2708.worm.columns;

import java.util.Objects;

public final class PrimaryKeyAttribute extends ColumnAttribute {

    private final String fieldName;
    private final String columnName;
    private final Class<?> fieldType;
    private final boolean autoGenerated;

    public PrimaryKeyAttribute(String fieldName, String columnName, Class<?> fieldType, boolean autoGenerated) {
        super(columnName, fieldType);

        this.fieldName = fieldName;
        this.columnName = columnName;
        this.fieldType = fieldType;
        this.autoGenerated = autoGenerated;
    }

    public String fieldName() {
        return fieldName;
    }

    public String columnName() {
        return columnName;
    }

    public Class<?> fieldType() {
        return fieldType;
    }

    public boolean autoGenerated() {
        return autoGenerated;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) return true;
        if (obj == null || obj.getClass() != this.getClass()) return false;
        var that = (PrimaryKeyAttribute) obj;
        return Objects.equals(this.fieldName, that.fieldName) &&
                Objects.equals(this.columnName, that.columnName) &&
                Objects.equals(this.fieldType, that.fieldType) &&
                this.autoGenerated == that.autoGenerated;
    }

    @Override
    public int hashCode() {
        return Objects.hash(fieldName, columnName, fieldType, autoGenerated);
    }

    @Override
    public String toString() {
        return "PrimaryKeyAttribute[" +
                "fieldName=" + fieldName + ", " +
                "columnName=" + columnName + ", " +
                "fieldType=" + fieldType + ", " +
                "autoGenerated=" + autoGenerated + ']';
    }
}