package de.paul2708.worm.attributes;

import de.paul2708.worm.attributes.generator.ValueGenerator;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGenerated {

    Class<? extends ValueGenerator<?>> value();
}
