package de.paul2708.worm.example.database;

import de.paul2708.worm.columns.*;
import de.paul2708.worm.columns.generator.ValueGenerator;
import de.paul2708.worm.database.DatabaseActionProcessor;
import de.paul2708.worm.database.memory.InMemoryDatabase;
import de.paul2708.worm.repository.actions.MethodInformation;
import de.paul2708.worm.repository.actions.SaveAction;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class DatabaseActionProcessorTest {

    private final DatabaseActionProcessor processor;

    public DatabaseActionProcessorTest() {
        this.processor = new DatabaseActionProcessor(new InMemoryDatabase(), StringEntity.class);
    }

    @Test
    void testValidLengths() {
        assertDoesNotThrow(() -> {
            simulateSave(new StringEntity("ABCD", "this is very long"));
        });
    }

    @Test
    void testInvalidLength() {
        assertThrows(IllegalStateException.class, () -> {
            simulateSave(new StringEntity("ABCD1234", "this is very long"));
        });
    }

    @Test
    void testCustomValueGenerator() {
        StringEntity entity = (StringEntity) simulateSave(new StringEntity("abcd", "random text"));

        assertEquals("auto generated", entity.autoGenerated);
    }

    private Object simulateSave(StringEntity entity) {
        return processor.process(new SaveAction(new MethodInformation(null, new Object[]{entity})));
    }

    @Table("strings")
    public static final class StringEntity {

        @Column("limited_text")
        @PrimaryKey
        @MaxLength(4)
        private String limitedText;

        @Column("arbitrary_text")
        private String arbitraryText;

        @Column("auto_generated")
        @AutoGenerated(ConstantValueGenerator.class)
        private String autoGenerated;

        public StringEntity() {

        }

        public StringEntity(String limitedText, String arbitraryText) {
            this.limitedText = limitedText;
            this.arbitraryText = arbitraryText;
        }
    }

    public static class ConstantValueGenerator implements ValueGenerator<String> {

        @Override
        public String generate() {
            return "auto generated";
        }
    }
}